### PR TITLE
Expose the parts of the personal identity number

### PR DESCRIPTION
**Pull request by mbergkvist**
**Type of change**

- [X] New feature
- [ ] Bug fix
- [ ] Security patch
- [ ] Documentation update

**Description**

Exposes the parts of the personal identity number; date, month, day, serial.

**Related issue**

None

**Motivation**

Having an instance of `Personnummer` means the personal identity number is successfully parsed. Having access to the parts of the personal identity number opens up for more usage of the `Personnummer`.

Similar api are available in the JS and Python projects.

**Checklist**

- [ ] I have read the **CONTRIBUTING** document.
- [X] I have read and accepted the **Code of conduct**
- [X] Tests passes.
- [X] Style lints passes.
- [X] Documentation of new public methods exists.

### CODE REVIEW

**Comment by mbergkvist** [comment]
@bombsimon Not sure if you are maintainer of this repo, but I'm tagging you here since you are the owner of upstream repo. My apologies if you already have been notified about this.

Is this PR of interest? We are currently using our fork, but we'd prefer to use upstream crate if possible.

**Comment by bombsimon** [comment]
Thanks! I am the maintainer and it looks reasonable to me to expose these fields!

I'll happily merge a PR for this feature. If it wasn't for the `is_coordination` and the fact it's already a method I wonder if exposing the struct fields would be nicer? Or if not, do you think it would make sense to add a method to return the full date and not just parts of it? I know the python implementation does this and others have their date field public. 

Either way I won't be able to publish a new release until Friday so I'll do the merge then!

**Comment by mbergkvist** [comment]
Actually, I did a PR on exposing the date, https://github.com/personnummer/rust/pull/12, but I then realized that it couples the `personnummer` api with `chrono`, and the client has to depend on `chrono` explicitly for the `Datelike` trait, and I didn't really like that, so I closed that PR.

I could look into replacing `chrono` with [std::time](https://doc.rust-lang.org/std/time/index.html) if you like.

**Comment by bombsimon** [comment]
Oh, sorry I missed that! I agree. 

If you think it's easy to move to  `std` that sounds like the right thing to do but if not I think the PR is good enough to merge.

If no changes or comments are added before Friday when I'm by my computer I merge it as is.

**Comment by mbergkvist** [comment]
> I could look into replacing `chrono` with [std::time](https://doc.rust-lang.org/std/time/index.html) if you like.

Well, that doesn't work, `std::time` was never meant to be used like that. I leave this PR as it is.

---

I noticed that `chrono` still depends on `time 0.1.44` , which has this voulnerability, https://rustsec.org/advisories/RUSTSEC-2020-0071. It doesn't affect this crate, but `cargo audit` reports the error anyway. Would you be interested in a PR that replaces `chrono` with `time 0.3` and adds a GH workflow that runs cargo audit regularly?

**Comment by bombsimon** [comment]
I have no strong opinion but it looks like `chrono` has a new maintainer and that they're actively trying to get back on track. They seem to drop dependency on `time` completely in https://github.com/chronotope/chrono/commit/4c351b1e720a30a6e32068fe386293b36d0e86fd that was made 2 weeks after the latest release.

The only reason to switch to `time` for me would be if it's more lightweight since we don't really need any advanced features for the date at all. Are there any reasons to switch to `time` instead of `chrono` other than the vulnerability?

**Comment by mbergkvist** [comment]
The sheer number of dependencies decreased with `time` but the binary size did actually increase and the rewriting needed for the adaption does not motivate to switch.

However, disabling default features in `chrono` and only enabling the features needed removed `time v0.1.44` and `libc v0.2.133` from the dependency tree. See #15

**Pull request merged**
